# Generated by Django 3.2.6 on 2021-12-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#9C9C9C', 'Серый'), ('#FFF68F', 'Желтый'), ('#00FF7F', 'Зеленый'), ('#FF6A6A', 'Красный'), ('#FF8247', 'Оранжевый'), ('#00F5FF', 'Синий')], max_length=7, unique=True, verbose_name='Цвет'),
        ),
    ]
